# Generated by Django 6.0.1 on 2026-01-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_ordertracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='cancellation_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='cancellation_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Cancellation Requested', 'Cancellation Requested'), ('Cancelled', 'Cancelled')], default='Active', max_length=25),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='refund_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='refund_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='refund_status',
            field=models.CharField(choices=[('No Request', 'No Request'), ('Requested', 'Requested'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='No Request', max_length=15),
        ),
    ]
