# Generated by GitHub Copilot on 2026-02-09
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderproduct_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertracking',
            name='status',
            field=models.CharField(choices=[('Order Confirmed', 'Order Confirmed'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Refund Requested', 'Refund Requested'), ('Cancellation Requested', 'Cancellation Requested'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned')], max_length=30),
        ),
    ]
