# Generated by GitHub Copilot on 2026-02-09
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_ordertracking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertracking',
            name='status',
            field=models.CharField(choices=[('Order Confirmed', 'Order Confirmed'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Refund Requested', 'Refund Requested'), ('Refund Approved', 'Refund Approved'), ('Refund Rejected', 'Refund Rejected'), ('Cancellation Requested', 'Cancellation Requested'), ('Cancellation Approved', 'Cancellation Approved'), ('Cancellation Rejected', 'Cancellation Rejected'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned')], max_length=30),
        ),
    ]
